#!/bin/bash -x
# creates a network namespace with openvpn and attaches a single application
# usage:
# vpn <your executable> <your parameters>
# Based on https://schnouki.net/post/2014/openvpn-for-a-single-application-on-linux/
# All credits to /dev/schnouki

# before executing this script:
# sudo su -
# mkdir -p /etc/netns/vpn
# echo 'nameserver 8.8.8.8' > /etc/netns/vpn/resolv.conf
# mkdir /etc/openvpn/config/
# copy ovpn config and auth files here 
# Change parameters below 

NETW=10.200.200.0/24
VPN0=10.200.200.1/24
VPN1=10.200.200.2/24
VIA=$(echo $VPN0 |cut -d'/' -f1)
ETH=enp0s31f6 # etherenet device find with #ip a
TUN=tun0 
CONFIG=/etc/openvpn/config/singapore-expressvpn-udp.ovpn # get this config from your vpn provider 
DAEMON=--daemon

if [ ! -f /run/netns/vpn ]; then
	#Create a new network namespace called vpn
    sudo ip netns add vpn
	#Start the loopback interface in the namespace
	sudo ip netns exec vpn ip addr add 127.0.0.1/8 dev lo
	sudo ip netns exec vpn ip link set lo up
	#Create virtual network interfaces 
	sudo ip link add vpn0 type veth peer name vpn1
	sudo ip link set vpn0 up
	sudo ip link set vpn1 netns vpn up
	sudo ip addr add $VPN0 dev vpn0
	sudo ip netns exec vpn ip addr add $VPN1 dev vpn1
	sudo ip netns exec vpn ip route add default via $VIA dev vpn1
fi

# Enable IPv4 routing and NAT for the interface in the namespace.
sudo iptables -A INPUT \! -i vpn0 -s $NETW -j DROP
sudo iptables -t nat -A POSTROUTING -s $NETW -o $ETH -j MASQUERADE
sudo sysctl -q net.ipv4.ip_forward=1

# start openvpn if TUN not there
if ! sudo ip netns exec vpn ip a | grep $TUN; then
	echo "starting the openvpn client"
	sudo ip netns exec vpn openvpn $DAEMON --config $CONFIG 
fi

# Wait for TUN to come up
while ! sudo ip netns exec vpn ip a | grep $TUN; do sleep .5; done
sudo ip netns exec vpn sudo -u $LOGNAME $1&
